user-message: "WARNING: This stack project is generated."

allow-newer: true
allow-newer-deps:
  - dhall
  - dhall-json

resolver: nightly-2024-05-18

packages:
  - ./.

extra-deps:
  - dhall-1.42.1
  - dhall-json-1.7.12
