project:
  type: website

website:
  title: hpack-dhall
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Introduction
      - href: cabal-commands.qmd
        text: Cabal Commands
      - href: linting.qmd
      - href: conditionals.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    syntax-definitions:
      - dhall.xml
