We provide 3 Cabal [external commands][external-commands] that operate
on any matching file input file in the source tree:

[external-commands]: https://cabal.readthedocs.io/en/latest/external-commands.html

- `dpack` matches on any `package.dhall` writing `<package-name>.cabal`.
- `ypack` matches on any `package.yaml` writing `<package-name>.cabal`.
- `diy-pack` matches on any `package.dhall` writing `package.yaml`.

::: {.callout-warning collapse="false"}
The `cabal.project` is not read or checked. These command finds any matching
`package.dhall` or matching `package.yaml` files in the current or child
directories but has options for excluding any of these or including files with
other names.
:::

These commands all have similar options:

### Options

- `--package-dhall GLOB` is a glob pattern to include when searching for files.
- `--ignore-glob GLOB` is a glob pattern to ignore when searching for files.

These can each be supplied multiple times. If `--package-dhall` is not supplied
it defaults to `**/package.dhall`.

## `dpack`

The "d" in this `dpack` command is so named for the "d" of the `.dhall`
extension.

This Cabal external command will generate `<package-name>.cabal` files for each
`package.dhall` file it finds in the current directory or any child directory.

## `ypack`

The "y" in this `ypack` command is so named for the "y" of the `.yaml`
extension.

::: {.callout-tip collapse="true"}
## Why is it not named "cabal-hpack"?
We're treating `cabal-hpack` as a reserved executable name and not named this
external command `hpack` in case Hpack wants to supply its own Cabal external
command.
:::

If a project only has `package.yaml` files and no `.cabal` files, then Stack
will happily generate the corresponding and needed `.cabal` files before doing
its build. Stack has Hpack built in. Cabal doesn't.

Stack will do the `.cabal` file generation on any matching `package.yaml` file
in a `stack.yaml` project. The `cabal-ypack` executable supplies this missing
feature to Cabal as an external command.

The standalone `hpack` executable operates on one or more input files. This
Cabal external command can be used instead of writing a script to find and pass
matching `package.yaml` files to `hpack`.

## `diy-pack`

This "diy" of this command is short for "d-i-y", for `.dhall` into `.yaml`.

If you already have `package.yaml` files but are thinking of using
`package.dhall` files instead, then this command can be used to generate the
`package.yaml` files as you undertake the conversion to ensure you effectively
have the same input.

::: {.callout-note collapse="false"}
If you already have `package.yaml` files and their matching `.cabal` files
checked in to source control then this command is likely not helpful except in
the case where you are debugging why the `.cabal` files differ when generated
from `package.dhall` files.
:::
