---
format:
  html:
    code-line-numbers: true
filters:
  - include-code-files
---

## Starting from Scratch

If you don't yet have a package, these can be created with `cabal init` or
`stack new`, picking one of the [Stack templates][stack-templates].

[cabal-init]: https://cabal.readthedocs.io/en/latest/cabal-commands.html#cabal-init
[stack-templates]: https://docs.haskellstack.org/en/stable/commands/templates_command/

The `package.yaml` file, `.cabal` file or both that these methods write can then
be used as the starting point for a translation to `package.dhall`, following
either the [starting from Cabal](@start-from-cabal) or [starting from
Hpack](@start-from-hpack) instructions.

Another option is picking someone else's package, with a `.cabal`,
`package.yaml` or possibly even a `package.dhall` and modifying it for your
purposes.

## Starting from Cabal {#start-from-cabal}

If you already have a package description in `.cabal` format and still want to
use `hpack-dhall`, you could either try to regenerate the `.cabal` file from a
`package.dhall` file you construct by hand or you could try using
[hpack-convert][hpack-convert] to convert to a `package.yaml` and then follow
the [Starting from Hpack](@start-from-hpack) instructions.

[hpack-convert]: https://github.com/yamadapc/hpack-convert

::: {.callout-caution collapse="true"}
## hpack-convert is Unmaintained

Last published to Hackage in 2017, `hpack-convert` is a fork of
[sol/hpack][sol-hpack].  There are unmerged pull requests on
[yamadapc/hpack-convert][hpack-convert-pulls], some of which mention getting it
building again, and it doesn't build with GHC versions, `8.2.* .. 9.14.*`.
:::

[sol-hpack]: https://github.com/sol/hpack
[hpack-convert-pulls]: https://github.com/yamadapc/hpack-convert/pulls

## Starting from Hpack {#start-from-hpack}

::: {.callout-caution}
## No Package Type Definition

There's no [Hpack schema][hpack-schema-issue] and we don't provide a type for
`package.dhall`.

[hpack-schema-issue]: https://github.com/sol/hpack/issues/521
:::

If you already have a `package.yaml` it should be pretty straightfoward to
translate this to `package.dhall`. If your `package.yaml` is small, translation
by hand is not too onerous. There's also a tool for conversion, `yaml-to-dhall`,
included in the `dhall-yaml` package. This can be installed with:

```{.txt code-line-numbers="false"}
$ cabal install dhall-yaml --ignore-project
```

This tool has quite a few options:

::: {.callout-note collapse="true"}
# yaml-to-dhall Options

```{.pre code-line-numbers="false"}
$ yaml-to-dhall --help
Usage: yaml-to-dhall [type | [SCHEMA] [--records-strict | --records-loose]
                       [--no-keyval-arrays] [--no-keyval-maps]
                       [--unions-first | --unions-none | --unions-strict]
                       [--omissible-lists] [--file FILE] [--output FILE]
                       [--ascii] [--plain] |
                       (-V|--version)]

  Convert a YAML expression to a Dhall expression, given the expected Dhall type

Available options:
  -h,--help                Show this help text
  SCHEMA                   Dhall type expression (schema)
  --records-strict         Fail if any JSON fields are missing from the expected
                           Dhall type
  --records-loose          Tolerate JSON fields not present within the expected
                           Dhall type
  --no-keyval-arrays       Disable conversion of key-value arrays to records
  --no-keyval-maps         Disable conversion of homogeneous map objects to
                           association lists
  --unions-first           The first value with the matching type (successfully
                           parsed all the way down the tree) is accepted, even
                           if not the only possible match. (DEFAULT)
  --unions-none            Unions not allowed
  --unions-strict          Error if more than one union values match the type
                           (and parse successfully)
  --omissible-lists        Tolerate missing list values, they are assumed empty
  --file FILE              Read YAML expression from a file instead of standard
                           input
  --output FILE            Write Dhall expression to a file instead of standard
                           output
  --ascii                  Format code using only ASCII syntax
  --plain                  Disable syntax highlighting
  -V,--version             Display version

Available commands:
  type                     Output the inferred Dhall type from a YAML value
```
:::

It can do the conversion and supply the type it infers, even with quite large
package descriptions, such as Stack's:

::: {.callout-note collapse="true"}
# Stack's Inferred Package Type
```{.pre filename=examples/stack/package-type.dhall include=../examples/stack/package-type.dhall code-block-bg="none" code-line-numbers="false"}
```
:::

::: {.callout-caution}
# Lexical Field Order
If we reorder the fields of the inferred type and supply this as a SCHEMA to
`yaml-to-dhall`, this has no effect on the resultant field order. Unfortunately,
your desired field order must be imposed by hand after the conversion.
:::

Without any configuration the fields will be sorted lexically but that will
likely not be what you want:

```{.dhall filename=examples/stack/package.dhall include=../examples/stack/package.dhall start-line=1 end-line=2}
```

```{.dhall include=../examples/stack/package.dhall start-line=71 end-line=85}
```

```{.dhall include=../examples/stack/package.dhall start-line=192 end-line=194}
```

```{.dhall include=../examples/stack/package.dhall start-line=368 end-line=372}
```

```{.dhall include=../examples/stack/package.dhall start-line=391 end-line=391}
```
