name: stack

on:
  push:
    branches: [ci-stack]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.4"]
        ghc:
          - "8.10.4"

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      name: setup stack
      with:
        enable-stack: true
        stack-version: 'latest'
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v2
      name: cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: build tests
      run: stack test --no-run-tests --no-terminal --stack-yaml=./stack/stack-${{ matrix.ghc }}.yaml

    - name: test golden
      run: stack test hpack-dhall:golden --no-terminal --test-arguments "--color=always" --stack-yaml=./stack/stack-${{ matrix.ghc }}.yaml

    - name: test hlint 
      run: stack test hpack-dhall:hlint --no-terminal --test-arguments "--color=always" --stack-yaml=./stack/stack-${{ matrix.ghc }}.yaml