name: stack

on:
  push:
    branches: [main, ci/check-versions]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ghc-${{ matrix.vers.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10.3.0"]
        vers:
          - {ghc: "9.8.2", stackage: "nightly-2024-05-18"}

    steps:
    - uses: actions/checkout@v4

    - name: Set up GHC and cabal-install from matrix
      uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: ${{ matrix.vers.ghc }}
        cabal-version: ${{ matrix.cabal }}
        enable-stack: true
        stack-version: '2.15.7'

    - name: Set up GHC 8.10.7 by itself
      uses: haskell-actions/setup@v2
      with:
        ghc-version: "8.10.7"

    - name: Check installation
      run: |
        ghc --version
        ghc-9.8.2 --version
        ghc-8.10.7 --version
        cabal --version
        stack --version
