name: stack

on:
  push:
    branches: [main, ci-stack]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ghc-${{ matrix.vers.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10.3.0"]
        vers:
          - {ghc: "9.8.2", stackage: "nightly-2024-05-18"}

    steps:
    - uses: actions/checkout@v4

    - name: Set up GHC 8.10.7 for scripts
      uses: haskell-actions/setup@v2
      with:
        ghc-version: "8.10.7"

    - name: Set up GHC and cabal-install
      uses: haskell-actions/setup@v2
      id: setup
      with:
        ghc-version: ${{ matrix.vers.ghc }}
        cabal-version: ${{ matrix.cabal }}
        enable-stack: true
        stack-version: '2.15.7'

    - name: Configure stack
      run: |
        stack config set system-ghc --global true
        stack config set install-ghc --global false
        stack config set resolver ${{ matrix.vers.stackage }}

    - name: Update hackage index
      run: cabal update --ignore-project

    - name: Install Dhall
      uses: dhall-lang/setup-dhall@v4
      with:
        version: '1.42.0'

    - name: Updo
      run: GHC_VERSION=${{ matrix.vers.ghc }} STACKAGE_VERSION=${{ matrix.vers.stackage }} make -f project-files.mk stack.yaml

    # Generate a file to cache dependencies.
    - name: build
      run: stack ls dependencies json | jq > stack-deps.json

    - name: build
      run: stack test --no-run-tests --no-terminal --only-dependencies

    - name: Restore cached dependency of Pantry (Stackage package index)
      uses: actions/cache/restore@v4
      id: pantry
      env:
        key: ghc-${{ steps.setup.outputs.ghc-version }}-stack-${{ steps.setup.outputs.stack-version }}
      with:
        path: ${{ steps.setup.outputs.stack-root }}/pantry
        key: ${{ env.key }}-plan-${{ hashFiles('stack-deps.json') }}
        restore-keys: ${{ env.key }}-

    - name: Recompute Stackage package index (~/.stack/pantry)
      if: steps.pantry.outputs.cache-hit != 'true'
      run: stack update

    - name: Save cached dependencies
      uses: actions/cache/save@v4
      if: steps.pantry.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.setup.outputs.stack-root }}/pantry
        key: ${{ steps.cache.outputs.cache-primary-key }}

    - name: build
      run: stack test --no-run-tests --no-terminal

    - name: test golden
      run: stack test hpack-dhall:golden --no-terminal --test-arguments "--color=always"
