name: stack

on:
  push:
    branches: [ci-stack]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.2"]
        ghc:
          - "8.8.3"

    steps:
    - uses: actions/checkout@v2

    - uses: mstksg/setup-stack@v1
      name: setup stack

    - name: cache key
      id: cache_key
      run: echo ::set-output name=key::$(md5sum stack.yaml | awk '{print $1}')

    - uses: actions/cache@v1
      name: cache ~/.stack
      id: cache
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ steps.cache_key.outputs.key }}

    - name: build tests
      run: stack test --no-run-tests --no-terminal

    - name: test golden
      run: stack test hpack-dhall:golden --no-terminal --test-arguments "--color=always"

    - name: test hlint 
      run: stack test hpack-dhall:hlint --no-terminal --test-arguments "--color=always"